# Generated by Django 4.2.11 on 2024-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Hight_School', 'High School'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree')], max_length=25, null=True),
        ),
    ]
