# Generated by Django 5.0.2 on 2024-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choices',
            field=models.ManyToManyField(to='quiz.choice'),
        ),
    ]
