# Generated by Django 5.0.2 on 2024-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choices',
        ),
    ]
