# Generated by Django 4.1.7 on 2024-02-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachloar', 'Bachloar Degree'), ('Master', 'Master Degree')], max_length=25, null=True),
        ),
    ]
